CREATE DATABASE LIBRARY_MANAGEMENT

USE LIBRARY_MANAGEMENT

go

CREATE TABLE USERS(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FIRSTNAME VARCHAR(20) NOT NULL,
	LASTNAME VARCHAR(20) NOT NULL,
	USERNAME VARCHAR(30) NOT NULL,
	USERPASSWORD VARCHAR(30) NOT NULL,
	USERTYPE VARCHAR(20) NOT NULL
)
create table ISSUE
(
     bookid int not null,
	 memid   int not null,
	 statut varchar(25)  ,
	 issue_date date not null,
	 return_date date not null,
	 note text,
)

alter table Issue add constraint fk_member_id foreign key (memid) references Members(id) on update cascade on Delete cascade;
delete from ISSUE
INSERT INTO USERS VALUES('PHAN', 'LAM', 'LAMPHAN', '123456', 'owner')
INSERT INTO USERS VALUES('NGUYEN', 'DOAN', 'DOANNGUYEN', '123456', 'admin')
INSERT INTO USERS VALUES('NGUYEN', 'HUY', 'HUYNGUYEN', '123456', 'admin')

SELECT * FROM users
SELECT * FROM AUTHORS

DELETE FROM USERS


CREATE TABLE GENRES(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NAME VARCHAR(120) NOT NULL
)

drop table GENRES

INSERT INTO GENRES VALUES('Trinh tham')
INSERT INTO GENRES VALUES('Kinh di')
SELECT * FROM GENRES
SELECT NAME FROM GENRES WHERE NAME = 'Kinh di'	
DELETE FROM GENRES 


CREATE TABLE AUTHORS (
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FIRSTNAME VARCHAR(20) NOT NULL,
	LASTNAME VARCHAR(20) NOT NULL,
	EDUCATION VARCHAR(50) NOT NULL,
	BIO TEXT 
)	

INSERT INTO AUTHORS VALUES('Phan', 'Lam', 'Student', 'hello xin chao moi nguoi')
INSERT INTO AUTHORS VALUES('Nguyen', 'Doan', 'Student', 'hello xin chao moi nguoi')
INSERT INTO AUTHORS VALUES('Nguyen', 'Huy', 'Student', 'hello xin chao moi nguoi')
SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) as FULLNAME FROM AUTHORS
select * from AUTHORS

CREATE TABLE BOOKS (
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ISBN VARCHAR(20) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	AUTHOR_ID INT NOT NULL,
	GENRE_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	PRICE MONEY NOT NULL,
	PUBLISHER TEXT NOT NULL,
	DATE_RECEIVED DATE NOT NULL,
	DESCRIPTION TEXT NOT NULL, 
	COVER IMAGE
)

DROP TABLE BOOKS

SELECT * FROM BOOKS

select sum(QUANTITY) as TONG_SACH from BOOKS where AUTHOR_ID = '2'

DELETE FROM BOOKS

select * from BOOKS b inner join GENRES g on b.GENRE_ID = g.ID

CREATE TABLE MEMBERS
(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FIRSTNAME VARCHAR(100) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	GENDER_MEMBER VARCHAR(10) NOT NULL,
	PHONE VARCHAR(25) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL
)

select * from MEMBERS

SELECT * FROM BOOKS WHERE AUTHOR_ID = 6 